#!/bin/bash

base_dir="/home/ifor/.dotfiles"
name="dotfiles"

echo "[${name}] Updating clients server."
ssh clients "git -C ${base_dir} config core.sshCommand 'ssh -i /home/ifor/.ssh/id_rsa' && git -C ${base_dir} pull"

echo "[${name}] Updating personal server."
ssh me "git -C ${base_dir} config core.sshCommand 'ssh -i /home/ifor/.ssh/id_rsa' && git -C ${base_dir} pull"

echo "[${name}] Updating tt server."
ssh tt "git -C ${base_dir} config core.sshCommand 'ssh -i /home/ifor/.ssh/ifor_tt' && git -C ${base_dir} pull"

echo "[${name}] Updating exped server."
ssh exped "git -C ${base_dir} config core.sshCommand 'ssh -i /home/ifor/.ssh/ifor_wmai' && git -C ${base_dir} pull"

base_dir="/home/cors/.dotfiles"
echo "[${name}] Updating cors server."
ssh cors "git -C ${base_dir} config core.sshCommand 'ssh -i /home/cors/.ssh/ifor_github' && git -C ${base_dir} pull"

echo "[${name}] Deploy complete!"
exit 0
