#!/bin/bash

GREEN='\033[0;32m'
NC='\033[0m'

base_dir=/home/ifor/.dotfiles
script_name=dotfiles
server=me

echo -e "${GREEN}[${script_name}] Updating termux-init files...${NC}"
rsync --verbose --no-times --compress \
  "${DOTFILES}/scripts/termux-init.sh" \
  "${DOTFILES}/scripts/yt" \
  "${DOTFILES}/bash/.bashrc" \
  "${DOTFILES}/termux/termux.properties" \
  "${server}:/var/www/downloads/termux"

echo -e "${GREEN}[${script_name}] [clients] Updating server...${NC}"
ssh clients "git -C ${base_dir} config core.sshCommand 'ssh -i /home/ifor/.ssh/id_rsa' && git -C ${base_dir} pull"

echo -e "${GREEN}[${script_name}] [karst-climber] Updating server...${NC}"
ssh karst "git -C ${base_dir} config core.sshCommand 'ssh -i /home/ifor/.ssh/id_rsa' && git -C ${base_dir} pull"

echo -e "${GREEN}[${script_name}] [personal] Updating server...${NC}"
ssh me "git -C ${base_dir} config core.sshCommand 'ssh -i /home/ifor/.ssh/id_rsa' && git -C ${base_dir} pull"

# echo -e "${GREEN}[${script_name}] [tt] Updating server...${NC}"
# ssh tt "git -C ${base_dir} config core.sshCommand 'ssh -i /home/ifor/.ssh/ifor_tt' && git -C ${base_dir} pull"

echo -e "${GREEN}[${script_name}] [cindra] Updating server...${NC}"
ssh cindra "git -C ${base_dir} config core.sshCommand 'ssh -i /home/ifor/.ssh/id_ed25519' && git -C ${base_dir} pull"

# echo -e "${GREEN}[${script_name}] [felix-weddings] Updating server...${NC}"
# ssh mpw "git -C ${base_dir} config core.sshCommand 'ssh -i /home/ifor/.ssh/id_ed25519' && git -C ${base_dir} pull"

echo -e "${GREEN}[${script_name}] [exped] Updating server...${NC}"
ssh exped "git -C ${base_dir} config core.sshCommand 'ssh -i /home/ifor/.ssh/ifor_wmai' && git -C ${base_dir} pull"

base_dir=/home/cors/.dotfiles
echo -e "${GREEN}[${script_name}] [cors] Updating server...${NC}"
ssh cors "git -C ${base_dir} config core.sshCommand 'ssh -i /home/cors/.ssh/ifor_github' && git -C ${base_dir} pull"

echo -e "${GREEN}[${script_name}] Deploy complete!${NC}"
exit 0
