#!/usr/bin/env bash

set -eo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'

script_name=TODO

local_dir=TODO
server=TODO
remote_dir=TODO

if ! [[ -d "$local_dir" ]]; then
  echo -e "${RED}[${script_name}] Directory not found, aborting...${NC}"
  exit 1
fi

echo -e "${GREEN}[${script_name}] All done!${NC}"
exit 0

