#!/usr/bin/env bash

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'

script_name=TODO

base_dir=TODO
server=TODO
dir=TODO

if ! [[ -d "$dir" ]]; then
  echo -e "${RED}[${script_name}] Directory not found, aborting...${NC}"
  exit 1
fi

echo -e "${GREEN}[${script_name}] All done!${NC}"
exit 0
