#!/usr/bin/env bash

name=PREFLIGHT
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "[${name}] This script must be run as root (or sudo). Exiting."
    exit 1
fi

home=/home/${SUDO_USER}
download_dir="${home}/downloads"
mkdir -p "${download_dir}"

echo "[${name}] Updating apt and upgrading packages."
apt update
apt upgrade -y

read -r -p "[${name}] Enter the new server hostname: " server_name
if [[ -z $server_name ]]; then
    echo "[${name}] Hostname cannot be empty."
    exit 1
fi
hostnamectl set-hostname $server_name

$home/.dotfiles/scripts/server/install_zsh
$home/.dotfiles/scripts/server/install_tmux
$home/.dotfiles/scripts/server/install_vim
$home/.dotfiles/scripts/server/install_utils
$home/.dotfiles/scripts/server/secure_ssh

echo "[${name}] All done, changing shell to zsh."

chsh -s $(which zsh)
