#!/usr/bin/env bash

name=MYSQL
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "[${name}] This script must be run as root (or sudo). Exiting."
    exit 1
fi

echo
read -r -p "[${name}] Enter new username: " new_user_name
if [[ -z $new_user_name ]]; then
    echo "[${name}] Username cannot be empty."
    exit 1
fi

echo -n "[${name}] Enter a password for ${new_user_name}: "
read -rs new_user_pass
echo
read -rs -p "[${name}] Confirm password: " NEW_USER_PASS_CONFIRM
if [ "${new_user_pass}" != "${NEW_USER_PASS_CONFIRM}" ]; then
    echo "[${name}] Passwords do not match."
    exit 1
fi

echo
read -r -p "[${name}] If you wish to create new databases, enter a space delimited list of their names: " new_databases

echo "[${name}] Installing."
apt install -y mysql-server

echo "[${name}] Imitating mysql_secure_installation"
mysql \
    --user=root \
    --execute="DELETE FROM mysql.user WHERE User=''; DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1'); DROP DATABASE IF EXISTS test; FLUSH PRIVILEGES;"

echo "[${name}] Creating new mysql user."
mysql \
    --user=root \
    --execute="CREATE USER '${new_user_name}'@'%' IDENTIFIED WITH mysql_native_password BY '${new_user_pass}'; GRANT ALL PRIVILEGES ON *.* TO '${new_user_name}'@'%';"

for db in "${new_databases[@]}"; do
    echo "[${name}] Creating new database: ${db}"
    mysql \
        --user=root \
        --execute="CREATE DATABASE ${db} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
done

echo "[${name}] All done!"
exit 0

