#!/usr/bin/env bash

name=PDF
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "[${name}] This script must be run as root (or sudo). Exiting."
    exit 1
fi

echo "[${name}] Installing required software."
apt install -y fontconfig libxrender1 xfonts-75dpi xfonts-base xfonts-utils libssl3

read -r -p "[${name}] Visit https://wkhtmltopdf.org/downloads.html and enter the appropriate download URL: " package_url

home=/home/${SUDO_USER}
filename=${package_url##*/}
download_dir=$home/downloads
mkdir -p $download_dir
download_path="${download_dir}/${filename}"

wget $package_url -O "${download_path}"

dpkg -i "${download_path}"

echo "[${name}] Copying binary to /usr/bin."
cp /usr/local/bin/wkhtmltopdf /usr/bin

echo "[${name}] Ensure \"'enable-local-file-access' => true\" is set when calling wkhtmltopdf."
echo "[${name}] All done!"
exit 0
