#!/usr/bin/env bash

name=UFW
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "[${name}] This script must be run as root (or sudo). Exiting."
    exit 1
fi

echo "[${name}] Installing."
apt install -y ufw

echo "[${name}] Setting up firewall rules."

ufw app list
ufw allow OpenSSH
ufw allow 'Nginx HTTP'
ufw allow 'Nginx HTTPS'
ufw enable

echo "[${name}] All done!"
exit 0

