#!/usr/bin/env bash

name=LEMP
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "[${name}] This script must be run as root (or sudo). Exiting."
    exit 1
fi

home=/home/${SUDO_USER}

echo "[${name}] Installing."
$home/.dotfiles/scripts/server/install_nginx
$home/.dotfiles/scripts/server/install_mysql
$home/.dotfiles/scripts/server/install_php
$home/.dotfiles/scripts/server/set_timezone
$home/.dotfiles/scripts/server/install_pdf
$home/.dotfiles/scripts/server/install_firewall

echo "[${name}] All done!"
exit 0
