#!/usr/bin/env bash

name=NGINX_FANCYINDEX
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "[${name}] This script must be run as root (or sudo). Exiting."
    exit 1
fi

echo "[${name}] Installing."

echo "[${name}] WIP Script, exiting."
exit 0
