#!/usr/bin/env bash

green='\033[0;32m'
cyan='\033[0;36m'
red='\033[0;31m'
nc='\033[0m'

name=CREATE_SSL_CERTIFICATE
usage="usage: ./create_ssl_certificate EMAIL WEB_ROOT DOMAIN [DOMAIN_2]"

email=$1
web_root=$2
domains="${@:3}"

function isEmailValid() {
    regex="^([A-Za-z]+[A-Za-z0-9]*((\.|\-|\_)?[A-Za-z]+[A-Za-z0-9]*){1,})@(([A-Za-z]+[A-Za-z0-9]*)+((\.|\-|\_)?([A-Za-z]+[A-Za-z0-9]*)+){1,})+\.([A-Za-z]{2,})+$"
    [[ "${1}" =~ $regex ]]
}

if [[ "$#" -lt 3 ]]; then
    echo -e "${red}[${name}] Please enter an email address, web root directory path and a space-delimited list of domains.${nc}"
    echo -e "${red}[${name}] ${usage}${nc}"
    exit 1
fi

if [[ -z "${email}" ]]; then
    echo -e "${red}[${name}] Please enter an email address.${nc}"
    echo -e "${red}[${name}] ${usage}${nc}"
    exit 1
fi

if ! isEmailValid "${email}"; then
    echo -e "${red}[${name}] Please enter a valid email address.${nc}"
    exit 1
fi

if [[ -z "${web_root}" ]]; then
    echo -e "${red}[${name}] Please enter the path to the root directory of your website.${nc}"
    echo -e "${red}[${name}] ${usage}${nc}"
    exit 1
fi

if [[ ! -d "${web_root}" ]]; then
    echo -e "${red}[${name}] '${web_root}' does not exist, aborting.${nc}"
    exit 1
fi

if [[ -z "${domains}" ]]; then
    echo -e "${red}[${name}] Please enter a domain name or list of domain names.${nc}"
    echo -e "${red}[${name}] ${usage}${nc}"
    exit 1
fi

if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo -e "${red}[${name}] This script must be run as root (or sudo). Exiting.${nc}"
    exit 1
fi

domain_args=""
for domain in $domains; do
    domain_args+="-d ${domain} "
done

if [[ ! -x $(which certbot) ]]; then
    echo -e "${red}[${name}] certbot not found.${nc}"
    read -p "Do you wish install certbot? (y/n) " -n 1 -r
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo
        echo -e "${cyan}[${name}] certbot not installed, aborting.${nc}"
        exit 1
    fi

    echo -e "${cyan}[${name}] Removing any old versions of certbot.${nc}"
    apt -y remove certbot

    echo -e "${cyan}[${name}] Installing cerbot.${nc}"
    snap install --classic certbot

    echo -e "${cyan}[${name}] Creating symlink for cerbot.${nc}"
    ln -s /snap/bin/certbot /usr/bin/certbot
fi

certbot certonly --webroot \
    -w "$web_root" \
    "$domain_args" \
    --non-interactive \
    --agree-tos \
    --email "$email" \
    --force-renewal

echo -e "${green}[${name}] All done! For these changes to be in effect please reload nginx.${nc}"
exit 0

