#!/usr/bin/env bash

RED='\033[0;31m'
GREEN='\033[0;32m'
# YELLOW='\033[0;33m'
NC='\033[0m'

script_name=fix-laravel-permissions
base_dir="$1"

if [[ ! -e "${base_dir}/artisan" ]]; then
  echo -e "${RED}[${script_name}] Not a Laravel installation, aborting...${NC}"
  exit 1
fi

# echo -e "${GREEN}[${script_name}] Setting ownership to ifor:www-data...${NC}"
# sudo chown -R ifor:www-data "$base_dir"

echo -e "${GREEN}[${script_name}] Setting directory permissions to 775...${NC}"
sudo find "$base_dir" -type d -exec chmod 775 {} \;

# echo -e "${GREEN}[${script_name}] Setting 'storage' and 'bootstrap/cache' directory permissions to 775...${NC}"
# sudo chmod -R 775 "${base_dir}/storage"
# sudo chmod -R 775 "${base_dir}/bootstrap/cache"

echo -e "${GREEN}[${script_name}] Setting file permissions to 664...${NC}"
sudo find "$base_dir" -type f -exec chmod 664 {} \;

echo -e "${GREEN}[${script_name}] Making artisan and deploy scripts executable...${NC}"
sudo chmod 755 "${base_dir}/"{artisan,deploy-remote,deploy-local}

echo -e "${GREEN}[${script_name}] All done!${NC}"
exit 0
