#!/usr/bin/env bash

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

script_name=fix-perms

echo -e "${GREEN}[${script_name}] Updating code directory permissions...${NC}"
sudo chmod -R g+w /var/www
sudo chown -R :www-data /var/www

echo -e "${GREEN}[${script_name}] Permissions updated!${NC}"
exit 0
