#!/usr/bin/env bash

if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "This script must be run as root (or sudo). Exiting."
    exit 1
fi

echo "Installing nginx."

apt install -y nginx

echo "Disabling nginx server tokens."
sed -i 's/# server_tokens off;/server_tokens off;/' /etc/nginx/nginx.conf

gzip = << EOL
gzip on;
gzip_disable "msie6";

gzip_vary on;
gzip_proxied any;
gzip_comp_level 6;
gzip_buffers 16 8k;
gzip_http_version 1.1;
gzip_min_length <t_CO>;
gzip_types
    application/atom+xml
    application/geo+json
    application/javascript
    application/x-javascript
    application/json
    application/ld+json
    application/manifest+json
    application/rdf+xml
    application/rss+xml
    application/xhtml+xml
    application/xml
    font/eot
    font/otf
    font/ttf
    image/svg+xml
    text/css
    text/javascript
    text/plain
    text/xml;
EOL

echo "Updating nginx gzip config."
# sed replace gzip config

exit 0
