#!/usr/bin/env bash

name=ZSH
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "[${name}] This script must be run as root (or sudo). Exiting."
    exit 1
fi

home=/home/${SUDO_USER}

echo "[${name}] Installing zsh."
apt install -y zsh

echo "[${name}] Installing oh-my-zsh."
sudo -u $SUDO_USER sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

echo "[${name}] Installing zsh plugins."
rm -rf $home/.dotfiles/zsh/plugins/zsh-autosuggestions;
rm -rf $home/.dotfiles/zsh/plugins/zsh-syntax-highlighting;
git clone --depth 1 https://github.com/zsh-users/zsh-autosuggestions $home/.dotfiles/zsh/plugins/zsh-autosuggestions;
git clone --depth 1 https://github.com/zsh-users/zsh-syntax-highlighting.git $home/.dotfiles/zsh/plugins/zsh-syntax-highlighting

echo "[${name}] Replacing default .zshrc with custom one."
rm -rf $home/.zshrc
ln -s $home/.dotfiles/zsh/.zshrc $home

echo "[${name}] All done!"
exit 0
