#!/usr/bin/env bash

name=NGINX_FANCYINDEX
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "[${name}] This script must be run as root (or sudo). Exiting."
    exit 1
fi

download_dir="/home/${SUDO_USER}/downloads/nginx"
nginx_verion=$(nginx -v 2>&1 | awk -F' ' '{print $3}' | cut -d / -f 2)

mkdir -p "${download_dir}"

echo "[${name}] Fetching nginx source."
wget "https://nginx.org/download/nginx-${nginx_verion}.tar.gz" -O "${download_dir}/nginx-${nginx_verion}.tar.gz"

echo "[${name}] Fetching fancyindex module."
git clone https://github.com/aperezdc/ngx-fancyindex.git "${download_dir}/ngx-fancyindex"

echo "[${name}] Fetching geoip module."
wget https://github.com/leev/ngx_http_geoip2_module/archive/refs/tags/3.3.tar.gz -O "${download_dir}/3.3.tar.gz"
tar xvfz "${download_dir}/3.3.tar.gz" -C "${download_dir}"

echo "[${name}] Installing."

echo "[${name}] All done!"
exit 0
