#!/usr/bin/env bash

name=TMUX
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "[${name}] This script must be run as root (or sudo). Exiting."
    exit 1
fi

home=/home/${SUDO_USER}

echo "[${name}] Installing."
apt install -y tmux

echo "[${name}] Creating symlinks."
ln -s $home/.dotfiles/tmux/.tmux.conf $HOME

echo "[${name}] All done!"
exit 0
