#!/usr/bin/env bash

if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "This script must be run as root (or sudo). Exiting."
    exit 1
fi

echo "Installing certbot."
snap install --classic certbot
ln -s /snap/bin/certbot /usr/bin/certbot

echo "Certbot installed!"

