#!/usr/bin/env bash

name=OPTIMISE_NGINX_DOMAIN_CONFIG
usage="usage: ./optimise_nginx_domain_config CONFIG_FILE"

config_file=$1
force_www=0

if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "[${name}] This script must be run as root (or sudo). Exiting."
    exit 1
fi

if [[ "$#" -lt 1 ]]; then
    echo "[${name}] Please enter the path to the nginx domain config file you wish to optimise."
    echo "[${name}] ${usage}"
    exit 1
fi

if [[ -d "$config_file" ]]; then
    echo "[${name}] Specified path is a directory, aborting."
    exit 1
fi

if [[ ! -e "${config_file}" ]]; then
    echo "[${name}] Config file does not exist, aborting."
    exit 1
fi

if [[ "$#" -eq 2 ]]; then
    echo "forcing www"
    exit 1
fi

echo "[${name}] Creating backup file for ${config_file}."
output_filepath="${config_file%/*}/.${config_file##*/}.bak"
output_filepath=${output_filepath/../.}
cp -v "$config_file" "${output_filepath}"

domain_name=$(sed -rn '/server_name/ s/server_name ([ a-z].*);/\1/p' "$config_file" | head -1 | xargs)

server_block_count=$(grep -c 'server ' "$config_file")
if [[ "$server_block_count" -gt 1 ]]; then
    echo "[${name}] Removing managed by certbot lines."
    tac "$config_file" | sed '0,/server {/d' | tac | sed '/# managed by Certbot/d;' | sed '/^$/N;/^\n$/D' > "$config_file".tmp
    mv -v "${config_file}.tmp" "$config_file"
fi

echo "[${name}] Removing listen directive."
sed -i '/listen/d' "$config_file"

sed -i "
/server /a\
    listen 443 ssl http2;\n\
\n\
    include h5bp\/tls\/ssl_engine.conf;\n\
    ssl_certificate \/etc\/letsencrypt\/live/${domain_name}\/fullchain.pem;\n\
    ssl_certificate_key \/etc\/letsencrypt\/live/${domain_name}\/privkey.pem;\n\
    include h5bp\/tls\/policy_strict.conf;\n\
\n\
" "$config_file"

echo
read -p "[${name}] Would you like to force www to non-www? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
   echo
   echo "[${name}] Updating config to force non-www URL."

sed -i "
1 i\
server {\n\
    listen 443 ssl http2;\n\
\n\
    server_name www.${domain_name};\n\
\n\
    include h5bp/tls/ssl_engine.conf;\n\
    ssl_certificate \/etc\/letsencrypt\/live/${domain_name}\/fullchain.pem;\n\
    ssl_certificate_key \/etc\/letsencrypt\/live/${domain_name}\/privkey.pem;\n\
    include h5bp/tls/policy_balanced.conf;\n\
\n\
    return 301 \$scheme://${domain_name}\$request_uri;\n\
}\n\n\
" "$config_file"
fi

echo "[${name}] All done!"
exit 0
