#!/usr/bin/env bash

name=OPTIMISE_PHP_FPM

if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "[${name}] This script must be run as root (or sudo). Exiting."
    exit 1
fi

php_version=${1:-$(php -r 'echo PHP_VERSION;' | awk -F. '{print $1"."$2}')}

fpm_config=/Users/ifor/Downloads/www.conf
fpm_config="/etc/php/${php_version}/fpm/pool.d/www.conf"

avg_request_usage_in_mb=${1:-50}
total_ram_in_mb=$(awk '/MemTotal/ {printf "%.1f\n", $2/1024 }' /proc/meminfo 2> /dev/null)
ram_buffer_pc=0.8
max_children=$(echo "${total_ram_in_mb} * ${ram_buffer_pc} / ${avg_request_usage_in_mb}"|bc)
start_servers=10
min_spare_servers=5
max_spare_servers=10
max_requests=500

if [[ ! -r "${fpm_config}" ]]; then
   echo "[${name}] Unable to read config file at ${fpm_config}"
   echo "[${name}] Aborting..."
   exit 1
fi

echo "[${name}] Active config file: ${fpm_config}"
echo
echo "[${name}] Current settings:"
grep '^;\?pm.max_children\|^;\?pm.start_servers\|^;\?pm.min_spare_servers\|^;\?pm.max_spare_servers\|^;\?pm.max_requests' "${fpm_config}"|grep -v ";"|sed 's/pm\.//'
echo
echo "[${name}] Proposed settings:"
echo "max_children = ${max_children}"
echo "start_servers = ${start_servers}"
echo "min_spare_servers = ${min_spare_servers}"
echo "max_spare_servers = ${max_spare_servers}"
echo "max_requests = ${max_requests}"
echo

read -p "[${name}] Do you want to update the FPM config file? (y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
   echo
   echo "[${name}] Aborting..."
   exit 1
fi

echo
echo "[${name}] Updating config file..."
sed -E "
   s/^;?pm.max_children.*$/pm.max_children = ${max_children}/;
   s/^;?pm.start_servers.*$/pm.start_servers = ${start_servers}/;
   s/^;?pm.min_spare_servers.*$/pm.min_spare_servers = ${min_spare_servers}/;
   s/^;?pm.max_spare_servers.*$/pm.max_spare_servers = ${max_spare_servers}/;
   s/^;?pm.max_requests.*$/pm.max_requests = ${max_requests}/;" "${fpm_config}
   " | \
   tee "${fpm_config}.temp" >/dev/null
mv "${fpm_config}.temp" "$fpm_config"

config_test=$(php-fpm${php_version} -t 2>&1|grep 'test is successful')
if [[ -z "${config_test}" ]]; then
   echo "[${name}] Config test failed, please manually check (php-fpm${php_version} -t) and try again."
   exit 1
fi

echo
echo "[${name}] Optimised settings:"
grep '^;\?pm.max_children\|^;\?pm.start_servers\|^;\?pm.min_spare_servers\|^;\?pm.max_spare_servers\|^;\?pm.max_requests' "${fpm_config}"|grep -v ";"|sed 's/pm\.//'

echo
read -p "[${name}] Settings updated, you need to restart the FPM service for these changes to take effect, restart now? (y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
   echo
   echo "[${name}] Service not restarted."
   exit 1
else
   echo
   echo "[${name}] Restarting FPM service"
   service "php${php_version}-fpm" restart
   echo
   echo "[${name}] All done!"
   exit 0
fi

