#!/usr/bin/env bash

name=SECURE_SSH
echo "[${name}] Current settings:"
grep -n 'PermitRootLogin\|PasswordAuthentication\|ChallengeResponseAuthentication\|UsePam' /etc/ssh/sshd_config|grep -v '#'
echo

read -p "[${name}] Do you want to update the sshd_config file? (y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
   echo
   echo "[${name}] Aborting..."
   exit 1
fi

echo
echo "[${name}] Disabling root login and password login"
sed '/^PermitRootLogin/s/yes/no/; /^PasswordAuthentication/s/yes/no/; /^ChallengeResponseAuthentication/s/yes/no/; /^UsePAM/s/yes/no/        ' /etc/ssh/sshd_config|sudo tee /etc/ssh/sshd_config >/dev/null

echo
echo "[${name}] Secured settings:"
grep -n 'PermitRootLogin\|PasswordAuthentication\|ChallengeResponseAuthentication\|UsePam' /etc/ssh/sshd_config|grep -v '#'

read -p "[${name}] Settings updated, you need to restart the ssh service for these changes to take effect, restart now? (y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
   echo
   echo "[${name}] Service not restarted."
else
   echo
   echo "[${name}] Restarting ssh service"
   sudo service ssh restart
   echo "[${name}] All done!"
fi

exit 0

