#!/usr/bin/env bash

name=TIMEZONE
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "[${name}] This script must be run as root (or sudo). Exiting."
    exit 1
fi

echo "[${name}] Current system timezone: $(cat /etc/timezone)"

read -r -p "[${name}] Enter timezone name: " user_timezone
available_timezones=$(awk '/^Z/ { print $2 }; /^L/ { print $3 }' /usr/share/zoneinfo/tzdata.zi)
if [[ -z $(echo $available_timezones | grep -w $user_timezone) ]]; then
    echo "[${name}] Not a recognised timezone. Use: 'timedatectl list-timezones' to view a list of available timezones."
    exit 1
fi

echo "[${name}] Setting system timezone to ${user_timezone}."
timedatectl set-timezone "${user_timezone}"
echo "[${name}] Updated system timezone: $(cat /etc/timezone)"

if [[ $(command -v php) ]]; then
    php_version=$(php -r 'echo PHP_VERSION;' | awk -F. '{print $1"."$2}')
    php_ini="/etc/php/${php_version}/fpm/php.ini"

    echo "[${name}] Current php timezone: $(php -r 'echo date_default_timezone_get().PHP_EOL;')"

    echo "[${name}] Found php, setting php-fpm timezone to ${user_timezone}."
    sed -i -E "s|^;?\s?date\.timezone\s?=.*$|date.timezone = ${user_timezone}|" $php_ini
    echo

    read -p "[${name}] Do you want to restart the service? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
       service "php${php_version}-fpm" restart
    fi
    echo "[${name}] Updated php timezone: $(php -r 'echo date_default_timezone_get().PHP_EOL;')"
fi

if [[ $(command -v mysql) ]]; then
    echo "Current mysql timezone: $(mysql -u root -B --disable-column-names -e 'SELECT @@global.time_zone;')"

    echo "[${name}] Found mysql, setting mysql timezone to ${user_timezone}."
    mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql mysql 2>/dev/null
    sed -i "/default-time-zone/d;/\[mysqld\]/a default-time-zone = ${user_timezone}" /etc/mysql/mysql.conf.d/mysqld.cnf

    read -p "[${name}] Do you want to restart the service? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
       service mysql restart
    fi
    echo "Updated mysql timezone: $(mysql -u root -B --disable-column-names -e 'SELECT @@global.time_zone;')"
fi

echo "[${name}] All done!"
exit 0
