#!/usr/bin/env bash

if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "This script must be run as root (or sudo). Exiting."
    exit 1
fi

echo "Setting up firewall rules."

ufw app list
ufw allow OpenSSH
ufw allow 'Nginx HTTP'
ufw allow 'Nginx HTTPS'
ufw enable

echo "Firewall set up."

exit 0
