#!/usr/bin/env bash

name=COMPOSER
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "[${name}] This script must be run as root (or sudo). Exiting."
    exit 1
fi

download_dir="/home/${SUDO_USER}/downloads"
mkdir -p "${download_dir}"

echo "[${name}] Installing."
php -r "copy('https://getcomposer.org/installer', '${download_dir}/composer-setup.php');"
php "${download_dir}/composer-setup.php"
php -r "unlink('${download_dir}/composer-setup.php');"

mv composer.phar /usr/local/bin/composer

echo "[${name}] All done!"
exit 0