#!/usr/bin/env bash

export HOME=/home/ifor

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'

fpm_version=8.3
script_name=PROJECT-local
base_dir="/var/www/${script_name/-local/}"

echo -e "${GREEN}[${script_name}] Enabling maintenance mode...${NC}"
php "${base_dir}/artisan" down

echo -e "${GREEN}[${script_name}] Removing fonts.bunny.net and cdn.tailwindcss.com references.${NC}"
for f in vendor/laravel/framework/src/Illuminate/Foundation/resources/exceptions/renderer/components/layout.blade.php \
  vendor/laravel/framework/src/Illuminate/Foundation/resources/health-up.blade.php; do
  if [[ ! -e "$f" ]]; then
    continue
  fi
  sed -i '/fonts.bunny.net/d' "${base_dir}/${f}"
  sed -i '/cdn.tailwindcss.com/d' "${base_dir}/${f}"
done

echo -e "${GREEN}[${script_name}] Fixing Translation Manager bugs.${NC}"
sed -i 's|\$group = basename($group)\;|\/\/ \$group =basename($group)\;|' "${base_dir}/vendor/barryvdh/laravel-translation-manager/src/Manager.php"
sed -i 's:\\JSON_PRETTY_PRINT | \\JSON_UNESCAPED_UNICODE):\\JSON_PRETTY_PRINT | \\JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES):' "${base_dir}/vendor/barryvdh/laravel-translation-manager/src/Manager.php"

echo -e "${GREEN}[${script_name}] Updating composer dependencies...${NC}"
composer --working-dir "$base_dir" install --no-interaction --optimize-autoloader --no-dev --prefer-dist

echo -e "${GREEN}[${script_name}] Running migrations...${NC}"
php "${base_dir}/artisan" migrate --force

echo -e "${GREEN}[${script_name}] Busting cache...${NC}"
php "${base_dir}/artisan" route:cache
php "${base_dir}/artisan" config:cache
php "${base_dir}/artisan" view:cache
# php "${base_dir}/artisan" queue:restart

echo -e "${GREEN}[${script_name}] Disabling maintenance mode...${NC}"
php "${base_dir}/artisan" up

fpm_bin="php-fpm${fpm_version}"
if ! [[ $(command -v "$fpm_bin") ]]; then
  echo -e "${RED}[${script_name}] Couldn't find ${fpm_bin}, do you have the correct version set?${NC}"
  exit 1
else
  echo -e "${GREEN}[${script_name}] Restarting php-fpm server...${NC}"
  SUDO_ASKPASS="${HOME}/.sdconfig" sudo -A systemctl reload "php${fpm_version}-fpm"
fi

echo -e "${GREEN}[${script_name}] All done!${NC}"
exit 0

