plugins: fetchart embedart convert scrub replaygain lastgenre chroma web
directory: /music
library: /config/musiclibrary.db
threaded: yes

paths:
    default: $albumartist/[$original_year] $album/$track - $title
    singleton: Non-Album/$artist - $title
    comp: Compilations/[$original_year] $album/$track - $title
    albumtype_soundtrack: Soundtracks/[$original_year] $album/$track $title

import:
    write: yes
    copy: no
    move: yes
    resume: ask
    incremental: yes
    quiet_fallback: skip
    timid: no
    log: ~/beet.log
