#!/bin/bash

source $HOME/.dotfiles/scripts/logger.sh

if [[ $(uname -a|grep "Darwin") ]]; then
  ppi "Installing using Homebrew"
  brew install curl
elif [[ $(uname -a|grep "Android") ]]; then
  ppi "Installing using pkg"
  pkg install curl
else
  ppi "Installing using apt-get"
  sudo apt-get install -y curl
fi

function install_from_src() {
    ppi "TODO"
}

# ppi "Creating symlink for .curl"
# rm -rf $HOME/.curl
# ln -s $HOME/.dotfiles/.curl $HOME/.curl
