#!/bin/bash

source $HOME/.dotfiles/scripts/logger.sh

if [[ $(uname -a|grep "Darwin") ]]; then
  ppi "Installing using Homebrew"
  brew install git
elif [[ $(uname -a|grep "Android") ]]; then
  ppi "Installing using pkg"
  pkg install git
else
  ppi "Installing using apt-get"
  sudo apt-get install -y git
fi

function install_from_src() {
    ppi "TODO"
}

ppi "Creating symlink for .gitconfig"
rm -rf $HOME/.gitconfig
ln -s $HOME/.dotfiles/.gitconfig $HOME/.gitconfig
