#!/bin/bash

source $HOME/.dotfiles/scripts/logger.sh

if [[ $(uname -a|grep "Darwin") ]]; then
  ppi "Installing using Homebrew"
  brew install mysql
elif [[ $(uname -a|grep "Android") ]]; then
  ppi "Installing using pkg"
  pkg install mysql
else
  ppi "Installing using apt-get"
  sudo apt-get install mysql
fi

function install_from_src() {
    ppi "TODO"
}

# ppi "Creating symlink for .mysql"
# rm -rf $HOME/.mysql
# ln -s $HOME/.dotfiles/.mysql $HOME/.mysql
