#!/bin/bash

source $HOME/.dotfiles/scripts/logger.sh

if [[ $(uname -a|grep "Darwin") ]]; then
  ppi "Installing using Homebrew"
  brew install node
elif [[ $(uname -a|grep "Android") ]]; then
  ppi "Installing using pkg"
  pkg install node
else
  ppi "Installing using apt-get"
  sudo apt-get install -y node
fi

function install_from_src() {
    ppi "TODO"
}

# ppi "Creating symlink for .node"
# rm -rf $HOME/.node
# ln -s $HOME/.dotfiles/.node $HOME/.node
