#!/bin/bash

source $HOME/.dotfiles/scripts/logger.sh

if [[ $(uname -a|grep "Darwin") ]]; then
  ppi "Installing using Homebrew"
  brew install tmux
elif [[ $(uname -a|grep "Android") ]]; then
  ppi "Installing using pkg"
  pkg install tmux
else
  ppi "Installing using apt-get"
  sudo apt-get install -y tmux
fi

ppi "Installing Tmux Resurrect"
rm -rf $HOME/.dotfiles/tmux/plugins/tmux-resurrect
git clone --depth 1 git@github.com:tmux-plugins/tmux-resurrect $HOME/.dotfiles/tmux/plugins/tmux-resurrect

# TODO - Install from source
function install_from_src() {
  ppi "Installing libevent"
  tar -zxf libevent-*.tar.gz
  cd libevent-*/
  ./configure --prefix=$HOME/local --enable-shared
  make && make install

  ppi "Installing ncurses"
  tar -zxf ncurses-*.tar.gz
  cd ncurses-*/
  ./configure --prefix=$HOME/local --with-shared --with-termlib --enable-pc-files --with-pkg-config-libdir=$HOME/local/lib/pkgconfig
  make && make install

  ppi "Downloading tmux tarball"

  ppi "Installing tmux..."
  tar -zxf tmux-*.tar.gz
  cd tmux-*/
  ./configure
  make && sudo make install
}

ppi "Creating symlink for .tmux.conf"
rm -rf $HOME/.tmux.conf
ln -s $HOME/.dotfiles/tmux/.tmux.conf $HOME/.tmux.conf
