#!/bin/bash

source $HOME/.dotfiles/scripts/logger.sh

if [[ $(uname -a|grep "Darwin") ]]; then
  ppi "Installing using Homebrew"
  brew install yarn
elif [[ $(uname -a|grep "Android") ]]; then
  ppi "Installing using pkg"
  pkg install yarn
else
  ppi "Installing using apt-get"
  sudo apt-get install -y yarn
fi

function install_from_src() {
    ppi "TODO"
}

# ppi "Creating symlink for .yarn"
# rm -rf $HOME/.yarn
# ln -s $HOME/.dotfiles/.yarn $HOME/.yarn
