#!/bin/bash

# echo 'Installing software...'
# pkg install tmux python php git file jq fzf rg wget htop ncat nmap tree vim zsh

echo 'Setting up symlinks...'

echo 'Setting up git'
git config --global user.email "ifor@cors.tech"
git config --global user.name "Ifor Waldo Williams"
git config --global init.defaultBranch "main"
