#!/bin/bash

echo 'Installing software...'
pkg install tmux python php git

echo 'Setting up symlinks...'

echo 'Setting up git'
git config --global user.email "ifor@cors.tech"
git config --global user.name "Ifor Waldo Williams"
git config --global init.defaultBranch "main"
