# Taps
tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-eid'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'

# Binaries
brew 'awscli'
brew 'arduino-cli'
brew 'binwalk'
brew 'cash-cli' # currency rates
brew 'cmus' # terminal player
brew 'colordiff'
brew 'coreutils' # Those that come with macOS are outdated
brew 'dfu-programmer' # Flashing Arduino bootloaders
brew 'dos2unix'
brew 'entr'
brew 'findutils'
brew 'gawk'
brew 'gnu-getopt'
brew 'gnu-indent'
brew 'gnu-sed'
brew 'gnu-tar'
brew 'gnutls'
brew 'grep'
brew 'httpie'
brew 'mackup'
brew 'mas' # Mac App Store manager
brew 'pandoc'
brew 'parallels'
brew 'pass'
brew 'pinentry-mac'
brew 'pkg-config' # https://github.com/driesvints/dotfiles/issues/20
brew 'reattach-to-user-namespace' # Required for tmux copy paste
brew 'shellcheck'
brew 'trash' # Manage the Trash bin
brew 'zlib' # Needed for Memcached

# Development
# brew 'php@7.2'
# brew 'php@7.3'
brew 'gifsicle'
brew 'jpegoptim'
brew 'mkcert'
brew 'optipng'
brew 'phpunit'
brew 'pngquant'
brew 'proxychains-ng'
brew 'stockfish'
brew 'svgo'
brew 'evince'

# Apps
cask 'alfred'
cask 'android-file-transfer'
cask 'android-studio'
cask 'arduino'
cask 'balsamiq-wireframes'
cask 'bartender'
cask 'clippy'
cask 'coda'
cask 'docker'
cask 'firefox'
cask 'github'
cask 'google-chrome'
cask 'handbrake'
cask 'insomnia'
cask 'iterm2'
cask 'java'
cask 'lilypond'
cask 'machoview'
cask 'midi-monitor'
cask 'moom'
cask 'ngrok'
cask 'obsidian'
cask 'postman'
cask 'sublime-text'
cask 'tableplus'
cask 'the-unarchiver'
cask 'tinkerwell'
cask 'transmission'
cask 'vagrant'
cask 'virtualbox' # Might need to allow access in Security settings
cask 'virtualbox-extension-pack'
cask 'vlc'

# Quicklook
cask 'qlcolorcode'
cask 'qlmarkdown'
cask 'qlstephen'
cask 'quicklook-csv'
cask 'quicklook-json'

# Fonts
cask 'font-fira-code'
cask 'font-lato'
cask 'font-open-sans'
cask 'font-roboto'

# Mac App Store
mas 'Bandwidth+', id: 490461369
mas 'Clocker', id: 1056643111
mas 'Microsoft Excel', id: 462058435
mas 'Microsoft PowerPoint', id: 462062816
# mas 'Microsoft Word', id: 462054704
mas 'Trello', id: 1278508951
mas 'WeChat', id: 836500024
mas 'Wunderlist', id: 410628904
