#!/usr/bin/env bash

source $DOTFILES/scripts/progress_bar.sh

if [ ! $1 ]; then
    echo "Enter knot name and number of images."
    exit 1
fi

echo "Preparing $1..."

if [ $3 ]; then
    name=$3
else
    name=$1
fi

mkdir $name 2>/dev/null

for i in $(seq 1 $2); do
    printf -v new_name "%sR%02d.jpg" $name $i
    printf -v url "https://www.animatedknots.com/photos/%s/%sR%d.jpg" $1 $1 $i

    progress $2 $i "Fetching images..."
    wget -q -O ./$name/$new_name $url
done

cp "${name}/${new_name}" "${name}/${name}R00.jpg"

echo "Done fetching, preparing gif..."

ffmpeg -loglevel quiet -framerate 1 -pattern_type glob -i "$name/*.jpg" -r 15 -vf scale=512:-1 "${name}/${name}.gif"

echo "All done!"
