#!/bin/bash

audio_path=${1:.}
csv="audio_data_$(date +%Y%m%d%H%M).csv"

echo "Writing audio data to ${csv}"

echo "filepath,mean_volume,max_volume" > $csv;
for f in "$audio_path"; do
    echo -n "${f}," >> $csv
    ffmpeg -i $f -af "volumedetect" -vn -sn -dn -f null /dev/null 2>&1 | \
    grep 'max_volume\|mean_volume' | \
    awk -F': ' '{print $2}' | \
    cut -d' ' -f1 | \
    paste -sd ',' >> $csv
done
