#!/usr/bin/env bash

remote_path="$1"

usage="usage: aws_cp <remote_path>"

if [[ $# -lt 2 ]]; then
    echo "Please supply a remote path."
    echo "$usage"
    exit 1
fi

aws s3 ls --summarize --human-readable --recursive s3://sblinsider > ~/Downloads/sbl_bucket.txt
aws s3 cp \
    --no-sign-request \
    --recursive \
     --exclude "*" \
     --include "$filter" \
    "s3://${remote_path}" \
    "$local_path"

echo "All done!"
exit 0

