#!/bin/bash

destination="/Users/ifor/Documents/backup/db_json"
today="$(date +%Y-%m-%d)"

echo "Backing up kuaidi..."
filename="backup_kuaidi_$(date +%Y-%m-%d)"
base_dir="/var/www/kuaidi/db"
rsync --verbose --times --compress "me:${base_dir}/*" "${destination}/kuaidi"

echo "Backing up ego buster..."
base_dir="/var/www/ego_buster"
rsync --verbose --times --compress "me:${base_dir}/results/*" "${destination}/ego_buster/results_${today}"

echo "Backing up jukebox..."
base_dir="/var/www/jukebox"
rsync --verbose --times --compress "me:${base_dir}/mb_db/*" "${destination}/jukebox/mb_db"
rsync --verbose --times --compress "me:${base_dir}/album_art/*" "${destination}/jukebox/album_art"
rsync --verbose --times --compress "me:${base_dir}/jukebox.sqlite" "${destination}/jukebox"

echo "Backing up darts stats..."
filename="backup_darts_stats_$(date +%Y-%m-%d)"
base_dir="/var/www/darts/db"
rsync --verbose --times --compress "me:${base_dir}/players.json" "${destination}/${filename}_players.json"
rsync --verbose --times --compress "me:${base_dir}/matches.json" "${destination}/${filename}_matches.json"

echo "Backing up pool stats..."
filename="backup_pool_stats_$(date +%Y-%m-%d)"
base_dir="/var/www/pool_stats/db"
rsync --verbose --times --compress "me:${base_dir}/players.json" "${destination}/${filename}_players.json"
rsync --verbose --times --compress "me:${base_dir}/matches.json" "${destination}/${filename}_matches.json"

echo "Backing up year planner..."
filename="backup_year_planner_$(date +%Y-%m-%d)"
base_dir="/var/www/year_planner/db"
rsync --verbose --times --compress "me:${base_dir}/data.json" "${destination}/${filename}_data.json"
rsync --verbose --times --compress "me:${base_dir}/workout.json" "${destination}/${filename}_workout.json"

echo "Backing up basketball shooting logger..."
filename="backup_bbsl_$(date +%Y-%m-%d)"
base_dir="/var/www/basketball_shooting_log"
rsync --verbose --times --compress "me:${base_dir}/bbsl.json" "${destination}/${filename}.json"

echo "Backing up pedalboard settings..."
rsync --verbose --times --compress -r me:/var/www/pedalboard/db/* "${destination}/pedbalboard"

