#!/usr/bin/env bash

script_name="backup-apps-list"
backup_dir="/Users/ifor/Documents/backup"
now=$(date "+%Y%m%d.%H%M%S")

if [[ $1 == 'android' ]]; then
  list=$(pbpaste)
  echo "[${script_name}] Parsing android apps..."
  android_file="${backup_dir}/installed.android.apps-${now}.txt"
  while read -r line; do
    echo "$line" | sed -E 's/\* \[(.*)\].*(q|id)=(.*)\)/\1 | \3/' >> "$android_file"
  done <<< $(pbpaste | grep "^*")
  cat "$android_file"
else
  echo "[${script_name}] Backing up Application folder apps list."
  /bin/ls -1v /Applications | sed 's/.app//' > "${backup_dir}/installed.mac.apps-${now}.txt"

  # echo "[${script_name}] Backing up brew installed apps list/."
  # brew leaves | xargs brew desc --eval-all > "${backup_dir}/installed.brew.apps-${now}.txt"
fi

echo "[${script_name}] All done!"
exit 0
