#!/usr/bin/env bash

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

src="${1:-/Volumes/IFOR2T}"
dest="${2:-/Volumes/IFOR2T_BACK}"
script_name=backup-hdd
exclude_list=(
  '.DS_Store'
  '.Trashes'
  '.fseventsd'
  '.TemporaryItems'
  '.Spotlight-V100'
  '.DocumentRevisions-V100'
)

if ! [[ -d "$src" ]]; then
  echo -e "${RED}[${script_name}] Source drive not found, aborting...${NC}"
  exit 1
fi

if ! [[ -d "$dest" ]]; then
  echo -e "${RED}[${script_name}] Destination drive not found, aborting...${NC}"
  exit 1
fi

echo -e "${GREEN}[${script_name}] HDD backup starting at $(date)${NC}"

/usr/local/bin/rsync \
  --archive \
  --no-perms \
  --no-owner \
  --no-group \
  --delete \
  --verbose \
  --human-readable \
  --executability \
  --stats \
  --compress \
  --ignore-errors \
  --log-file=/Users/ifor/logs/backup-hdd.log \
  "${exclude_list[@]/#/--exclude=}" \
  "${src}/" \
  "${dest}"

if [[ "$?" -eq 0 ]]; then
  echo -e "${GREEN}[${script_name}] HDD backup completed at $(date)${NC}"
  exit 0
else
  echo -e "${RED}[${script_name}] HDD backup failed.${NC}"
  exit 1
fi

