#!/usr/bin/env bash

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

SOURCE="${1:-/Volumes/IFOR2T}"
DEST="${2:-/Volumes/IFOR2T_BACKUP}"

script_name=backup-hdd

if ! [[ -d "$SOURCE" ]]; then
    echo -e "${RED}[${script_name}] Source drive not found, aborting...${NC}"
    exit 1
fi

if ! [[ -d "$DEST" ]]; then
    echo -e "${RED}[${script_name}] Destination drive not found, aborting...${NC}"
    exit 1
fi

echo -e "${GREEN}[${script_name}] HDD backup starting at $(date)${NC}"

rsync \
    --archive \
    --human-readable \
    --verbose \
    --executability \
    --acls \
    --delete \
    --stats \
    --ignore-errors \
    --exclude={'.Trashes','.TemporaryItems','.Spotlight-V100','.fseventsd','.DocumentRevisions-V100','.DocumentRevisions-V100'}
    "${SOURCE}/" \
    "${DEST}" \
    2>&1 | tee /Users/ifor/backup-hdd.log

if [[ "$?" -eq 0 ]]; then
    echo -e "${GREEN}[${script_name}] HDD backup completed at $(date)${NC}"
    exit 0
else
    echo -e "${RED}[${script_name}] HDD backup failed.${NC}"
    exit 1
fi

