#!/bin/bash

input_folder="${1:-/Users/ifor/Downloads}"
output_folder="${1:-/Users/ifor/Movies}"

function clean() {
    src="$1"
    folder="$2"
    dest="$(echo "$src" | sed -E "s/(.*[0-9]{4}).*/\1/;s:^${folder}/:${folder}/_:;s/ /\./g;s/\(//g;s/__/_/g")"
    if [[ -n $DEBUG ]]; then
        echo "DRY RUN - No files modified."
    else
        mv "$src" "$dest"
    fi
    echo "$src" "--->" "$dest"
}
export -f clean
find "${input_folder}" -maxdepth 1 -regextype sed -regex ".*[0-9]\{4\}.*" -print0 | xargs -0 -I {} bash -c "clean '{}' '${output_folder}'"
