#!/usr/bin/env bash

dl_folder="${HOME}/storage/downloads"
reddit_folder="${dl_folder}/reddit"
script_name="clean-reddit-dls"

if ! [[ -e "$dl_folder" ]]; then
  echo "[${script_name}] Android downloads folder not found, aborting..."
  exit 1
fi

echo "[${script_name}] Moving Reddit downloads to own folder..."
mv -v "$dl_folder"/RDT_* "$reddit_folder"

echo "[${script_name}] All done!"
exit 0
