#!/usr/bin/env bash

orange='\033[0;33m'
green='\033[0;32m'
red='\033[0;31m'
nc='\033[0m'

name="CONCAT_MEDIA"
usage="usage: concat_media OUTPUT_FILENAME INPUT_FILES"

output_filename=$1

if [[ "$#" -lt 2 ]]; then
    echo -e "${red}[${name}] Missing required args.${nc}"
    echo -e "${red}[${name}] ${usage}${nc}"
    exit 1
fi

echo -e "${orange}[${name}] The following files will be merged to ${output_filename}${nc}"
for file in "${@:2}"; do
    echo "- ${file}"
done
read -p "Are you sure you want to continue? (y/n) " -n 1 -r
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo
    echo -e "${red}[${name}] Aborting.${nc}"
    exit 1
fi

ffmpeg -f concat -safe 0 -i <(printf "file '$(pwd)/%s'\n" "${@:2}") -c copy "$output_filename"

echo -e "${green}[${name}] All done!${nc}"
