#!/bin/bash

password_file="/home/ifor/mysql_pass"
if [[ ! -r "$password_file" ]]; then
  echo "Cannot find MySQL password file, aborting."
  exit 1
fi

backup_dir=/home/ifor/backups
user=${1:-root}
hostname="127.0.0.1"
now=$(date +"%F")
password=$(cat "$password_file")

databases=$(mysql -h $hostname -u $user -p$password -s -N -e "SHOW DATABASES;" | grep -v "information_schema\|mysql\|performance_schema\|sys")

[ ! -d $backup_dir ] && mkdir -p $backup_dir

echo 'Backing up databases...'

for db in $databases; do
  file="${backup_dir}/${db}.sql.gz"
  filedate=

  [ -f "$file" ] && filedate=$(date -r "$file" +"%F")
  [ "$filedate" == "$now" ] && [[ -z $1 ]] && continue

  [ -f "$file" ] && mv "$file" "${file}.old"

  mysqldump --single-transaction --routines --quick -h $hostname -u $user -p$password -B "$db" | gzip > "$file"

  rm -f "${file}.old"
done

echo 'Backup success!'
