#!/usr/bin/env bash

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'

server=SERVER
script_name=PROJECT
remote_dir="/var/www/${script_name}"

echo -e "${GREEN}[${script_name}] Running git pull...${NC}"
ssh "$server" "git -C ${remote_dir} config core.sshCommand 'ssh -i /home/ifor/.ssh/id_rsa' && git -C ${remote_dir} pull"

echo -e "${GREEN}[${script_name}] Building assets...${NC}"
npm run build

echo -e "${GREEN}[${script_name}] Copying build files to remote...${NC}"
rsync \
  --verbose \
  --compress \
  --recursive \
  --omit-dir-times \
  --times \
  public/build/* \
  "${server}:${remote_dir}/public/build"
# rsync \
#   --verbose \
#   --compress \
#   --recursive \
#   --omit-dir-times \
#   --no-perms \
#   --times \
#   storage/app/public/* \
#   "${server}:${remote_dir}/storage/app/public"

echo -e "${GREEN}[${script_name}] Running deploy script on remote...${NC}"
ssh "$server" "${remote_dir}/deploy-local"

echo -e "${GREEN}[${script_name}] All done!${NC}"
exit 0
