#!/usr/bin/env python3.11

from bs4 import BeautifulSoup
import re, sys, requests

if len(sys.argv) < 2:
    exit("[ERROR] Missing url.")

url = sys.argv[1]


s = requests.Session()
s.headers = {
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:120.0) Gecko/20100101 Firefox/120.0',
    'Accept': 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
    'Accept-Language': 'en-GB',
    'Accept-Encoding': 'gzip, deflate, br',
    'Connection': 'keep-alive',
    'Upgrade-Insecure-Requests': '1',
    'Sec-Fetch-Dest': 'document',
    'Sec-Fetch-Mode': 'navigate',
    'Sec-Fetch-Site': 'cross-site',
    'DNT': '1',
    'Sec-GPC': '1',
    'Pragma': 'no-cache',
    'Cache-Control': 'no-cache',
}
r = s.get(url)
data = r.content

soup = BeautifulSoup(data, 'html.parser')
containers = soup.findAll("div", {"class" : re.compile('Lyrics__Container.*')})
lyrics = ""
for container in containers:
    lyrics += "\n".join(container.findAll(string=True, recursive=True))

lyrics = lyrics.replace("[", "\n\n[").replace("\n\n\n", "\n\n").strip()
print(lyrics)
