#!/usr/bin/env python3

from bs4 import BeautifulSoup
import re, sys, requests, os
import urllib.request

s = requests.Session()

filepath = '/Users/ifor/Downloads/Ed.Friedland.Bass.Method.html'
with open(filepath) as fp:
    soup = BeautifulSoup(fp, 'html.parser')
    # for anchor in soup.findAll('a', {'class' : 'mp3FileExt42'}, href=re.compile('.*Bass_Method.*')):
    for anchor in soup.findAll('a', {'class' : 'mp3FileExt42'}, href=re.compile('.*\d{2}_online.*')):
        print(anchor)
        r = s.get(anchor['href'])
        data = r.content
        # print(data)

        soup2 = BeautifulSoup(data, 'html.parser')
        new_filename = "ed.fr1edland.bass.method.book.3."+re.sub(' - MP3 Download.*', '', soup2.title.string).replace(" ", ".").replace(".-.", ".").replace(".(Hal.Leonard)", "").replace(".book", ".b0").lower().replace("iii", "3").replace("ii", "2").replace("i", "1")+".mp3"
        print(new_filename)

        audio_url = soup2.find('input', {"class": "jsD1PreviewUrl"}, type="hidden")['value']
        print(audio_url)
        new_filepath = "/Users/ifor/Downloads/ed.friedland.bass.method.audio/"+new_filename
        if os.path.exists(new_filepath):
            continue

        urllib.request.urlretrieve(audio_url, new_filepath)
        # exit()

print("All done!")
exit()
