#!/usr/bin/env bash

server=me
filepath="$1"
remote_dir="$2"

if [[ -z "$filepath" ]]; then
  echo "Enter the path to a file, usage: iup <filepath> [remote_dir]"
  exit 1
fi

if [[ ! -e "$filepath" ]]; then
  echo "File not found, aborting."
  exit 1
fi

filename=$(basename "$filepath")
remote_path="/var/www/downloads/${remote_dir}"

echo "Uploading file..."
rsync -avz --progress "$filepath" "${server}:${remote_path}"

echo "Setting file permissions..."
ssh "$server" "chmod 644 '${remote_path}/${filename}' && chown :www-data '${remote_path}/${filename}'"

echo "All done!"
exit 0
