#!/usr/bin/env bash

set -o errexit  # Exit the script if any command fails (add "|| true" to allow failing)
set -o nounset  # Exit the script if an undeclared variable is used
set -o pipefail # Exit the script if an error occurs in a pipe
# set -o xtrace # Enable bash debug output
# set -o verbose # Enable verbose output

# Default options
remote_folder="DominoApiBackup"
local_folder="$(pwd)"
bucket="dc-materials"

usage() {
    cat <<MSG

    Download the latest file in an S3 folder.

    Usage: ./latest_s3_file [options]

    Options:
        -b, --bucket <name>         Name of your S3 bucket.
        -r, --remote-folder <path>  The full path to your rbackup directory.
        -l, --local-folder <path>   Full path to your local download directory.
        -p, --profile <name>        S3 profile if not using your default profile.
        -h, --help                  Display this usage information.

MSG
}

# Parse arguments
while [ $# -gt 0 ]; do
    case "$1" in
        -b|--bucket)
            bucket="${2%/}"
            ;;
        -r|--remote-folder)
            remote_folder="${2%/}"
            ;;
        -l|--local-folder)
            local_folder="${2%/}"
            ;;
        -p|--profile)
            profile="--profile=${2}"
            ;;
        -h|--help)
            usage
            exit 1
            ;;
    esac
    shift
done

echo "Connecting to S3, if the script ends without warning, no file was found, please check your args list and try again."
echo
latest=$(
# shellcheck disable=2086
    aws s3 ls "${bucket}/${remote_folder}/" ${profile:-} --human \
        | sort -rn \
        | head -1
)

if [[ -z "${latest}" ]]; then
    echo "Failed to find any files in ${remote_folder}."
    exit 1
fi

filesize=$(echo "${latest}" | awk '{ print $3,$4 }')
filename=$(echo "${latest}" | awk '{ print $5 }')
remote_filepath="${bucket}/${remote_folder}/${filename}"

echo "Attempting to download ${remote_filepath} (${filesize}) to ${local_folder}."
echo
# shellcheck disable=2086
aws s3 cp "s3://${remote_filepath}" "${local_folder}" ${profile:-}

