#!/usr/bin/env bash

name="MuseScore PDF"
ms_dir="/Users/ifor/Documents/MuseScore4"
output_dir="/Users/ifor/Downloads"
filepath="$1"
filename="${filepath##*/}"
filename="${filename%.*}"

if [[ ! -r "$filepath" ]]; then
  echo "Unable to read file, aborting."
  exit 1
fi

if [[ $# -gt 1 ]]; then
  echo "Handling tab only, score only or both"
  if [[ $2 == 'all' ]]; then
    # echo "Showing staff"
    unzip -p $filepath "${filename}.mscx" \
      | sed 's:<isStaffVisible>0</isStaffVisible>:<isStaffVisible>1</isStaffVisible>:' \
      > "${filename}.mscx"
  else
    # echo "Hiding staff"
    unzip -p $filepath "${filename}.mscx" \
      | sed 's:<isStaffVisible>1</isStaffVisible>:<isStaffVisible>0</isStaffVisible>:' \
      > "${filename}.mscx"
  fi
  zip $filepath "${filename}.mscx"
  rm -v "${filename}.mscx"
fi

echo "[${name}] Converting to PDF."
/Applications/MuseScore\ 4.app/Contents/MacOS/mscore -o "${output_dir}/${filename}.pdf" -S "${ms_dir}/Styles/my_style.mss" "$filepath"

open "${output_dir}/${filename}.pdf"

echo "[${name}] All done!"
exit 0
