#!/bin/bash

mysql_version="$(mysqld -V | awk '{print substr($3,0,1) substr($3,3,1)}')"
if [[ "$mysql_version" -lt 80 ]]; then
  echo "mysql less than v8.0"; exit
  mysql_statement="USE mysql; UPDATE user SET authentication_string='${password}' WHERE User='root'; UPDATE user SET plugin='mysql_native_password' WHERE User='root'; FLUSH PRIVILEGES; quit"
else
  echo "mysql is v8.0 or newer"; exit
  mysql_statement="USE mysql; UPDATE user SET authentication_string=null WHERE User='root'; FLUSH PRIVILEGES; ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '${password}'; FLUSH PRIVILEGES; quit"
fi


