#!/usr/bin/env bash

name="Remove Password"
password=$1
input_file=$2
output_file=$3

if [[ $# -lt 3 ]]; then
    echo "Missing required arguments."
    echo "usage: ./pdf-remove-password <password> <input_file> <output_file>"
    exit 1
fi

echo "[${name}] Removing password."
qpdf --password="$password" --decrypt "$input_file" "$output_file"

echo "[${name}] All done!"
exit 0
