#!/bin/bash

filename="pedalboard_backup" #_$(date +%Y-%m-%d)"
destination="/Users/ifor/Documents/backup"

scp -r me:/home/ifor/code/pedalboard/db/* "$destination/pedbalboard/"

#echo "${destination}/${filename}.json"

