#!/bin/bash

filename="pedalboard_backup" #_$(date +%Y-%m-%d)"
destination="/Users/ifor/Documents/backup"

scp -r clients:/home/ifor/code/pedal_board/db/* "$destination/pedbalboard/"

#echo "${destination}/${filename}.json"

