#!/usr/bin/env python3

import random

shot_rounds = [
    "Name the Band",
    "Name the Sport",
    "Name the Celebrity",
    "Name the Landmark",
    "Name the Animal",
    "Name the Flag",
    "Yangshuo landmarks with no names",
]

categories = [
    "Animals",
    "Art",
    "Celebrities",
    "Food & Drink",
    "General Knowledge",
    "Geography",
    "History",
    "Language",
    "Literature",
    "Movies",
    "Music",
    "Mythology",
    "On This Day",
    "Religion",
    "Riddles",
    "Science",
    "Technology",
    "True or False",
    "Yangshuo",
]

random.shuffle(shot_rounds)
random.shuffle(categories)

print("Selected Categories:")
for index, cat in enumerate(categories[:6]):
    print(index + 1, cat)

print("\nSelected Shot Round:")
print(shot_rounds[0])

