#!/bin/bash

if ! [ "$(id -u)" = 0 ]; then
   echo "This script needs to be run as root or sudo." >&2
   exit 1
fi

while true; do
  read -r -s -p "New root password: " password
  echo
  read -r -s -p "New root password confirmation: " password_confirmation
  echo

  if [ "$password" != "$password_confirmation" ]; then
    echo "Passwords do not match, please try again." && continue
  fi

  if [ -z "$password" ]; then
    echo "[Warning] Setting empty password."
  fi

  break
done

echo "New root password: ${password}"

echo "Stopping current MYSQL service..."
service mysql stop

mkdir -p /var/run/mysqld
chown mysql:mysql /var/run/mysqld

echo "Starting MYSQL daemon..."
mysqld_safe --skip-grant-tables --skip-networking &

jobs

echo "Updating root password..."
mysql -u root -e "FLUSH PRIVILEGES; USE mysql; UPDATE user SET authentication_string=PASSWORD('${password}') WHERE User='root'; UPDATE user SET plugin='mysql_native_password' WHERE User='root'; FLUSH PRIVILEGES; quit"

echo "Killing daemon process..."
pkill mysqld

echo "Starting MYSQL service..."
service mysql start
