#!/bin/bash

DEBUG=1
declare -x DEBUG

file_type="${1:-*}"
file_depth="${2:-1}"

function clean() {
    LANG=C

    src="$1"
    dest=$(echo $src | sed "
        s/^\.\//XXXX/;
        s/^\.\/\./XXXX/;
        s/[^[:alnum:]_\/\ \.-]//g;
        s/_/\./g;
        s/  / /g;
        s/ - /-/g;
        s/\.-\./-/g;
        s/ /\./g;
        s/\.\././g;
        s/^XXXX/\.\//
    ")
    dest="${dest,,}"

    if [[ $DEBUG != 1 ]]; then
        mv "${src}" "${dest}"
    fi

    echo "${src}" "--->" "${dest}"
}

export -f clean

find . \
    -maxdepth "$file_depth" \
    -type f \
    -name "$file_type" \
    -print0 | \
    xargs -0 -I {} bash -c "clean \"{}\""

echo
read -p "Do you want to rename these files? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    DEBUG=0
    echo
    find . \
        -maxdepth "$file_depth" \
        -type f \
        -name "$file_type" \
        -print0 | \
        xargs -0 -I {} bash -c "clean \"{}\""
fi

