#!/bin/bash

DEBUG=1
declare -x DEBUG

function clean() {
    LANG=C

    src="$1"
    dest=$(echo $src | sed "
        s/^\.\//XXXX/;
        s/^\.\/\./XXXX/;
        s/[^[:alnum:]_\/\ \.-]//g;
        s/_/\./g;
        s/  / /g;
        s/ - /-/g;
        s/\.-\./-/g;
        s/ /\./g;
        s/\.\././g;
        s/^XXXX/\.\//
    ")
    dest="${dest,,}"

    if [[ $DEBUG != 1 ]]; then
        mv "${src}" "${dest}"
    fi

    echo "${src}" "--->" "${dest}"
}

export -f clean

find . -type f \( -name '*.webm' -o -name '*.flv' -o -name '*.mkv' -o -name '*.mp3' -o -name '*.pdf' -o -name '*.mp4' -o -name '*.wav' \) -print0 | \
    xargs -0 -I {} bash -c "clean \"{}'\""

echo
read -p "Do you want to rename these files? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    DEBUG=0
    echo
    find . -type f \( -name '*.webm' -o -name '*.flv' -o -name '*.mkv' -o -name '*.mp3' -o -name '*.pdf' -o -name '*.mp4' -o -name '*.wav' \) -print0 | \
        xargs -0 -I {} bash -c "clean \"{}\""
fi

