#!/usr/bin/env python3

import math
import argparse
from datetime import datetime, timedelta, timezone, date
from zoneinfo import ZoneInfo


def sunrise_sunset(lat, lon, date_obj, tz_name="UTC"):
    n = date_obj.timetuple().tm_yday
    lat_rad = math.radians(lat)

    gamma = 2 * math.pi / 365 * (n - 1)

    eot = (229.18 * (
        0.000075 +
        0.001868 * math.cos(gamma) -
        0.032077 * math.sin(gamma) -
        0.014615 * math.cos(2 * gamma) -
        0.040849 * math.sin(2 * gamma)
    ))

    decl = (
        0.006918 -
        0.399912 * math.cos(gamma) +
        0.070257 * math.sin(gamma) -
        0.006758 * math.cos(2 * gamma) +
        0.000907 * math.sin(2 * gamma) -
        0.002697 * math.cos(3 * gamma) +
        0.00148 * math.sin(3 * gamma)
    )

    cos_ha = (
        math.cos(math.radians(90.5667)) /
        (math.cos(lat_rad) * math.cos(decl))
        - math.tan(lat_rad) * math.tan(decl)
    )

    cos_ha = min(1, max(-1, cos_ha))
    ha = math.degrees(math.acos(cos_ha))

    solar_noon = 720 - 4 * lon - eot

    sunrise_min = solar_noon - ha * 4
    sunset_min = solar_noon + ha * 4

    tz = ZoneInfo(tz_name)

    def to_time(minutes):
        dt_utc = datetime.combine(date_obj, datetime.min.time(), tzinfo=timezone.utc)
        dt_utc += timedelta(minutes=minutes)
        return dt_utc.astimezone(tz).time()

    return to_time(sunrise_min), to_time(sunset_min)


def parse_date(date_str):
    return datetime.strptime(date_str, "%Y-%m-%d").date()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Sunrise/Sunset calculator")

    parser.add_argument("lat", type=float, help="Latitude")
    parser.add_argument("lon", type=float, help="Longitude")
    parser.add_argument("date", type=str, help="Date in YYYY-MM-DD")
    parser.add_argument("--tz", type=str, default="UTC", help="IANA timezone (default UTC)")

    args = parser.parse_args()

    d = parse_date(args.date)

    sr, ss = sunrise_sunset(args.lat, args.lon, d, tz_name=args.tz)

    print(d)
    print("Sunrise:", sr)
    print("Sunset :", ss)
