#!/bin/bash

local_path="${1:-/Users/ifor/Movies}"
remote_path="${2:-/Volumes/IFOR2T/videos}"

for f in kids movies tv; do
    local_filelist="/tmp/sync_movies_local_filelist_${f}"
    remote_filelist="/tmp/sync_movies_remote_filelist_${f}"

    find "${local_path}/${f}/" -mindepth 1 -maxdepth 1 -type d -printf '%P\n' | sed 's/^_//' | sort > "${local_filelist}"
    find "${remote_path}/${f}/" -mindepth 1 -maxdepth 1 -type d -printf '%P\n' | sed 's/^_//' | sort > "${remote_filelist}"

    echo "The following directories are not present in the ${f} remote directory."
    comm -23 $local_filelist $remote_filelist
    echo
done

exit 0
