#!/bin/bash

local_path="/Users/ifor/Movies"
remote_path="/Volumes/IFOR2T/videos"

for f in kids movies tv; do
    local_filelist="/tmp/sync_movies_local_filelist_${f}"
    remote_filelist="/tmp/sync_movies_remote_filelist_${f}"

    find "${local_path}/${f}/" -mindepth 1 -maxdepth 1 -type d -printf '%P\n' | sed 's/^_//' > "${local_filelist}"
    find "${remote_path}/${f}/" -mindepth 1 -maxdepth 1 -type d -printf '%P\n' | sed 's/^_//' > "${remote_filelist}"

    diff $local_filelist $remote_filelist
done

exit 0
