#!/usr/bin/env bash

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'

script_name=sync-darts-audio

remote_dir=/Volumes/IFOR2T/darts/en-GB-Russ-Male-v1
local_dir=/Users/ifor/darts-hub/darts-caller-media/en-GB-Russ-Male-v1

if ! [[ -d "$remote_dir" ]] || ! [[ -d "$local_dir" ]]; then
  echo -e "${RED}[${script_name}] Directory not found, aborting...${NC}"
  exit 1
fi

echo -e "${GREEN}[${script_name}] Syncing audio files...${NC}"
rsync --archive --verbose --recursive --compress "$remote_dir" "$local_dir"

echo -e "${GREEN}[${script_name}] All done!${NC}"
exit 0

