#!/usr/bin/env php
<?php
$headers_raw =
  "Name|MajorDiameter|MinorDiameter|ThreadPitch|ThreadPitchFine|PitchDiameter|TappingDrillDiameter|ClearanceHoleDiameter";

$raw_data = "
M1   | 1.0  | 0.729  | 0.25 | 0.2           | 0.838  | 0.75  | 1.3
M1.1 | 1.1  | 0.829  | 0.25 | 0.2           | 0.938  | 0.85  | 1.4
M1.2 | 1.2  | 0.929  | 0.25 | 0.2           | 1.038  | 0.95  | 1.5
M1.4 | 1.4  | 1.075  | 0.30 | 0.2           | 1.205  | 1.10  | 1.8
M1.6 | 1.6  | 1.221  | 0.35 | 0.2           | 1.373  | 1.25  | 2.0
M1.8 | 1.8  | 1.421  | 0.35 | 0.2           | 1.573  | 1.45  | 2.3
M2   | 2.0  | 1.567  | 0.40 | 0.25          | 1.740  | 1.60  | 2.6
M2.2 | 2.2  | 1.713  | 0.45 | 0.25          | 1.908  | 1.75  | 2.9
M2.5 | 2.5  | 2.013  | 0.45 | 0.35          | 2.208  | 2.05  | 3.1
M3   | 3.0  | 2.459  | 0.50 | 0.35          | 2.675  | 2.50  | 3.6
M3.5 | 3.5  | 2.850  | 0.60 | 0.35          | 3.110  | 2.90  | 4.2
M4   | 4.0  | 3.242  | 0.70 | 0.5           | 3.545  | 3.30  | 4.8
M4.5 | 4.5  | 3.688  | 0.75 | 0.5           | 4.013  | 3.80  | 5.3
M5   | 5.0  | 4.134  | 0.80 | 0.5           | 4.480  | 4.20  | 5.8
M6   | 6.0  | 4.917  | 1.00 | 0.75          | 5.350  | 5.00  | 7.0
M7   | 7.0  | 5.917  | 1.00 | 0.75          | 6.350  | 6.00  | 8.0
M8   | 8.0  | 6.647  | 1.25 | 1--0.75       | 7.188  | 6.80  | 10.0
M9   | 9.0  | 7.647  | 1.25 | 1--0.75       | 8.188  | 7.80  | 11.0
M10  | 10.0 | 8.376  | 1.50 | 1.25--1--0.75 | 9.026  | 8.50  | 12.0
M11  | 11.0 | 9.376  | 1.50 | 1--0.75       | 10.026 | 9.50  | 13.5
M12  | 12.0 | 10.106 | 1.75 | 1.5--1.25--1  | 10.863 | 10.20 | 15.0
M14  | 14.0 | 11.835 | 2.00 | 1.5--1.25--1  | 12.701 | 12.00 | 17.0
M16  | 16.0 | 13.835 | 2.00 | 1.5--1        | 14.701 | 14.00 | 19.0
M18  | 18.0 | 15.394 | 2.50 | 2--1.5--1     | 16.376 | 15.50 | 22.0
M20  | 20.0 | 17.294 | 2.50 | 2--1.5--1     | 18.376 | 17.50 | 24.0
M22  | 22.0 | 19.294 | 2.50 | 2--1.5--1     | 20.376 | 19.50 | 26.0
M24  | 24.0 | 20.752 | 3.00 | 2--1.5--1     | 22.051 | 21.00 | 28.0
M27  | 27.0 | 23.752 | 3.00 | 2--1.5--1     | 25.051 | 24.00 | 33.0
M30  | 30.0 | 26.211 | 3.50 | 3--2--1.5     | 27.727 | 26.50 | 35.0
M33  | 33.0 | 29.211 | 3.50 | 3--2--1.5     | 30.727 | 29.50 | 38
M36  | 36.0 | 31.670 | 4.00 | 3--2--1.5     | 33.402 | 32.00 | 41
M39  | 39.0 | 34.670 | 4.00 | 3--2--1.5     | 36.402 | 35.00 | 44
M42  | 42.0 | 37.129 | 4.50 | 4--3--2       | 39.077 | 37.50 | 47
M45  | 45.0 | 40.129 | 4.50 | 4--3--2       | 42.077 | 40.50 | 50
M48  | 48.0 | 42.857 | 5.00 | 4--3--2       | 44.752 | 43.00 | 53
M52  | 52.0 | 46.587 | 5.00 | 4--3--2       | 48.752 | 47.00 | 57
M56  | 56.0 | 50.046 | 5.50 | 4--3--2       | 52.428 | 50.50 | 61
M60  | 60.0 | 54.046 | 5.50 | 4--3--2       | 56.428 | 54.50 | 65
M64  | 64.0 | 57.505 | 6.00 | 4--3--2       | 60.103 | 58.00 | 69
M68  | 68.0 | 61.505 | 6.00 | 4--3--2       | 64.103 | 62.00 | 73
";

if (count($argv) < 3) {
  exit(
    "usage: ./thread_dimensions.php <diameter (mm)> <length (mm)> [pitch: coarse (default), fine, finer, finest]" .
      PHP_EOL
  );
}

$diameter = "M{$argv[1]}";
$length = $argv[2];

$headers = explode("|", $headers_raw);
array_shift($headers);
$data = [];
foreach (explode("\n", $raw_data) as $line) {
  if (!$line) {
    continue;
  }

  $bolt_data = explode("|", $line);
  $name = trim(array_shift($bolt_data));
  $data[$name] = array_combine(
    $headers,
    array_map(fn($item) => trim($item), $bolt_data)
  );
}

function mm_to_inch($value)
{
  return ($value / 25.4) * 1000;
}

if (!isset($data[$diameter])) {
  exit("{$diameter} not in lookup table.");
}

$thread_fine_pitches = explode("--", $data[$diameter]["ThreadPitchFine"]);
$thread_pitch_type = $argv[3] ?? "coarse";
$thread_height = 0.5;

switch ($thread_pitch_type) {
  case "fine":
    $thread_pitch = $thread_fine_pitches[0];
    break;
  case "finer":
    $thread_pitch = $thread_fine_pitches[1] ?? $thread_fine_pitches[0];
    break;
  case "finest":
    $thread_pitch = array_pop($thread_fine_pitches);
    break;
  default:
    $thread_pitch = $data[$diameter]["ThreadPitch"];
}

$base_dir = "/Users/ifor/Documents/sketchup/whorl_db";

@mkdir($base_dir);

$output_file = "{$base_dir}/{$diameter}x{$thread_pitch}x{$length}.wrl";

$end_radius = mm_to_inch($data[$diameter]["MajorDiameter"] / 2);
$start_radius = $end_radius;
$no_of_tapered_r = 0;
$no_of_fixed_r = $length / $thread_pitch - $thread_height;
$thread_pitch = mm_to_inch($thread_pitch);
$sections_per_r = 48;
$thread_height = mm_to_inch($thread_height); // Placeholder value
$thread_length = mm_to_inch(
  ($data[$diameter]["MajorDiameter"] - $data[$diameter]["MinorDiameter"]) / 2
);
$thread_edge = mm_to_inch(0); // Placeholder value

$string = <<<DATA
{$end_radius}
{$start_radius}
{$thread_pitch}
{$no_of_tapered_r}
{$no_of_fixed_r}
{$sections_per_r}
{$thread_height}
{$thread_length}
{$thread_edge}
DATA;

file_put_contents($output_file, $string);

echo <<<MSG
RAW DATA
===============
{$string}
===============


MSG;

print_r($data[$diameter]);

echo PHP_EOL . "Written to WRL file: {$output_file}" . PHP_EOL;

