#!/usr/bin/env bash

source $HOME/.dotfiles/scripts/logger.sh

readonly session="${1}"

if [[ -z $session ]]; then
    log_w "Session name required, available sessions:"
    find $HOME/.dotfiles/tmux/sessions -type f -printf "    - %f\n" \
        | sed "s/.sh$//" \
        | sort
    exit 1
fi

$HOME/.dotfiles/tmux/sessions/$session.sh

log "$session up and running!"
