#!/usr/bin/env bash

# shellcheck source=/dev/null
source "${HOME}/.dotfiles/scripts/logger.sh"

readonly session="${1}"

if [[ -z $session ]]; then
    log_w "Session name required, available sessions:"
    find "${HOME}/.dotfiles/tmux/sessions" -type f -printf "    - %f\n" \
        | sort
    exit 1
fi

"${HOME}/.dotfiles/tmux/sessions/${session}"

log "${session} up and running!"
