#!/usr/bin/env bash

base_dir="/Users/ifor/Downloads/jukebox"
remote_dir="/var/www/jukebox/album_art"

echo "Optimising images."
for f in "$base_dir"/*.jpg; do
  cp -v "$f" "${f/.jpg/_orig.jpg}"
  magick convert -quality 75 -geometry 1200x\> "${f/.jpg/_orig.jpg}" "${f/_orig.jpg/.jpg}"
  magick convert -quality 75 -geometry 240x\> "${f/.jpg/_orig.jpg}" "${f/.jpg/_thumb.jpg}"
  rm -v "${f/.jpg/_orig.jpg}"
done

echo "Uploading images."
scp "$base_dir"/*.jpg "me:${remote_dir}"

echo "All done!"

exit 0

