#!/usr/bin/env bash

osascript -e "display notification \"Checking virtual machine status...\" with title \"VirtualBox\""

vbid="${1:-f9ed162}"
status=$(/usr/local/bin/vagrant status "$vbid" --machine-readable | grep state, | cut -d, -f4)

if [[ "$status" == "poweroff" ]]; then
    osascript -e "display notification \"Virtual machine is booting up...\" with title \"VirtualBox\""
    /usr/local/bin/vagrant up "$vbid"
else
    osascript -e "display notification \"Virtual machine is shutting down...\" with title \"VirtualBox\""
    /usr/local/bin/vagrant halt "$vbid"
fi

