#!/usr/bin/env bash

set -o pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'
REPLACE='\e[1A\e[K'

script_name=website-ping
output_file=/tmp/website_pings
websites=(
  bikeasia.com
  booking.indier.net
  cindra.se
  cors.tech
  dominochinese.com
  expednet.cn
  felixweddings.com
  husfokus.com
  iforwms.com
  indier.net
  indier.org
  karstclimber.com
  kimtaichichina.com
  plan.cindra.se
  portal.karstclimber.com
  theindier.org
  thyme.cors.tech
  wildmed.asia
  wmai.wildmed.asia
  yangshuotaichi.com
)

if [[ $# -eq 0 ]]; then
  longest_url=-1
  for site in ${websites[@]}
  do
    if [ ${#site} -gt $longest_url ]
    then
      longest_url=${#site}
    fi
  done

  echo -n > "$output_file"
  for site in "${websites[@]}"; do
    site_padded=$(printf "%-${longest_url}s" "${site}")
    start_millis=$(date +%s%3N)
    echo -e "${YELLOW}[${script_name}] ${site_padded} | Checking...${NC}"
    status_code=$(curl -sL --head -w "%{http_code}\n" "$site" -o /dev/null)
    status_color="$GREEN"
    if [[ "$status_code" != "200" ]]; then
      status_color="$RED"
      echo "$site" >> "$output_file"
    fi
    duration=$(printf "%5s" $(($(date +%s%3N) - $start_millis)))
    echo -e "${REPLACE}${status_color}[${script_name}] ${site_padded} | ${duration}ms | ${status_code}${NC}"
  done
  echo -e "${GREEN}[${script_name}] All done!${NC}"
else
  if [[ -e "$output_file" ]] && [[ ! -s "$output_file" ]]; then
    echo "{'text':'All OK!', 'font_color': '101,232,134,255'}"
  else
    echo "{'text':'$(cat "$output_file")', 'font_color': '255, 72, 72,255'}"
  fi
fi
exit 0

