#!/usr/bin/env bash

# RED='\033[0;31m'
GREEN='\033[0;32m'
# YELLOW='\033[0;33m'
NC='\033[0m'

SCRIPT_DIR=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)
script_name=wifi-token-refresh

echo -e "${GREEN}[${script_name}] Refreshing token...${NC}"
res=$(curl 'http://192.168.1.1/' --silent -X POST --data-raw 'frashnum=&action=login&Frm_Logintoken=5&username=user&logincode=Gsl%2BpaCG7O%2BGUzaTfDzFCifhps3eRKASlPVEmJl8I59cQVfz3lWcf6gTsk4%2FVWy8WUIuMTPd4IDp1CiFnrpt%2FcwbmCBxWtYjRgjezJtXwqLZePeu9BaExOcj4LkSCfTyQ27Si2OFKGhZTSUMjz3vE%2F03oZ1cw9IjAnSnH1bqPZ4%3D&usr=OxnLcjDe9FaKfzpgxe8TKKhD8xcWPsIgXFXM97%2B81xunn%2BCODbuSXoB51ThrkKS3mJPqeDuuRny9QwWv%2F8lYlScmuB6cEV3OX5O0dSdbVKaZvVza9ZKud1oHSKdL8ZKv2KSMh4QepIl5BwbBX%2Fd%2BYEqTmI60s61DRyQYRLoPTYA%3D&ieversion=1')
token=$(echo "$res" | sed -n 's/.*USER_LOG_TOKEN=" + "\([0-9A-Z]\+\)";.*/\1/p')

echo -e "${GREEN}[${script_name}] Setting token to \"${token}\"...${NC}"
"${SCRIPT_DIR}/wifi-token" "$token"

echo -e "${GREEN}[${script_name}] All done!${NC}"
exit 0


