#!/usr/bin/env bash

# RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

# script_name=wifi-devices

router_reponse=$(
  curl \
    --silent 'http://192.168.1.1/web/cmcc/gch/status_terminal_info_gch.gch' \
    -H 'Cookie: USER_LOG_TOKEN=A4967909593760471; ADMIN_LOG_TOKEN=A9599088703776728'
)
devices=$(
  echo "$router_reponse" \
    | sed 's/></\n/g' \
    | grep 'devName\|ipAddr\|macAddr' \
    | sed '
      s/.*>\(.*\)<.*/\1/;
      s/iMac-Ifor/Ifor\|iMac/;
      s/Macbook-Ifor/Ifor\|Macbook/;
      s/KKG-AN70/Ifor\|Phone/;
      s/WLZ-AN00/Meiling\|Phone/;
      s/nova_6_(5G)-919b263c8cc38/Meiling\|Phone/;
      s/WGRR-W19/Mia\|Pad/;
      s/XTC_D2/Mia\|Watch-New/;
      s/XTC_Z5q/Mia\|Watch-Old/;
      s/MiTV4-ANSM0-1cdda1ed3b579347/-\|MiTV/;
      s/Z6/Noa\|Watch/
    ' \
    | paste -d'|' - - - \
    | sort --ignore-case
)
device_count=$(echo "$devices" | wc -l)

if [[ -n "$1" ]]; then
  echo "$devices" | sed 1d | sed 's/\[0;32m//' | cut -d\| -f1 | sort -u
  exit 0
fi

echo -e "Connected devices (${device_count}) [User|Device|IP|MAC]"
echo -e "${GREEN}${devices}${NC}"

exit 0

