#!/usr/bin/env bash

# RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

# script_name=wifi-devices

router_reponse=$(
  curl \
    --silent 'http://192.168.1.1/web/cmcc/gch/status_terminal_info_gch.gch' \
    -H 'Cookie: USER_LOG_TOKEN=A4967909593760471; ADMIN_LOG_TOKEN=A9599088703776728'
)
devices=$(
  echo "$router_reponse" \
    | sed 's/></\n/g' \
    | grep 'devName\|ipAddr\|macAddr' \
    | sed '
      s/.*>\(.*\)<.*/\1/;
      s/iMac-Ifor/IforiMac/;
      s/Macbook-Ifor/IforMacbook/;
      s/KKG-AN70/IforPhone/;
      s/WLZ-AN00/WLZ-AN00/;
      s/nova_6_(5G)-919b263c8cc38/MeilingPhone/;
      s/WGRR-W19/MiaPad/;
      s/XTC_D2/MiaWatchNew/;
      s/XTC_Z5q/MiaWatchOld/;
      s/MiTV4-ANSM0-1cdda1ed3b579347/MiTV/;
      s/Z6/NoaWatch/
    ' \
    | paste -d'|' - - - \
    | sort --ignore-case
)
device_count=$(echo "$devices" | wc -l)

echo -e "Connected devices (${device_count}) [Name|IP|MAC]"
echo -e "${GREEN}${devices}${NC}"

exit 0

