#!/usr/bin/env bash

script_name="yt"
url="$1"

if [[ -z "$url" ]]; then
  echo "[${script_name}] usage: yt <url>";
  exit 1
fi

options=(
  "Normal Download"
  "Download MP3 to current directory"
  "Download to current directory"
  "Download to current directory and clean up filename"
  "Download to current directory and convert video audio to MP3"
  "Quit"
)

echo "[${script_name}] Select download type:"
select opt in "${options[@]}"
do
    case $opt in
        "Normal Download")
            echo "[${script_name}] Downloading file to default directory..."
            output_filename=$(basename "$(yt-dlp --get-filename "$url")")
            yt-dlp $url
            exit 0
            ;;
        "Download MP3 to current directory")
            echo "[${script_name}] Downloading file and extracting audio to current directory..."
            output_filename=$(basename "$(yt-dlp --get-filename "$url")")
            yt-dlp -x --audio-format mp3 -P . $url
            $DOTFILES/scripts/sbl_cleanup_filename "${output_filename/.mkv/.mp3}" FORCE
            exit 0
            ;;
        "Quit")
            echo "[${script_name}] Exiting..."
            exit 0
            ;;
        *)
          echo "[${script_name}] Invalid option ${REPLY}. Aborting..."
          echo "[${script_name}] usage: yt <url>";
          exit 1
         ;;
    esac
done
